POST https://eastus.api.cognitive.microsoft.com/speechtotext/v3.2/transcriptions/
Ocp-Apim-Subscription-Key: 7cguxqsRWHtwh1P0IAsSlYzTK5dSdhSNsePTqxblqOQUsOtL50YbJQQJ99BCACYeBjFXJ3w3AAAYACOG2C0A
Content-Type: application/json

{
"contentContainerUrl": "texttospeachrga4da.blob.core.windows.net/",
        "locale": "en-CA",
        "displayName": "My Transcription",
        "properties": {
            "diarizationEnabled": "True",
            "destinationContainerUrl": "http://test.com?wdifhisdf",
            "wordLevelTimestampsEnabled": "True",
            "timeToLiveHours": "48"

        }
}

###

GET https://eastus.api.cognitive.microsoft.com/speechtotext/v3.2/transcriptions/3e11ec9a-f7dd-47b0-868c-af10e3171b98
Ocp-Apim-Subscription-Key: 7cguxqsRWHtwh1P0IAsSlYzTK5dSdhSNsePTqxblqOQUsOtL50YbJQQJ99BCACYeBjFXJ3w3AAAYACOG2C0A
Content-Type: application/json
###

GET https://eastus.api.cognitive.microsoft.com/speechtotext/v3.2/transcriptions/5a2b4c39-0a38-49f9-8ecc-17a7983cf573/files
Ocp-Apim-Subscription-Key: 7cguxqsRWHtwh1P0IAsSlYzTK5dSdhSNsePTqxblqOQUsOtL50YbJQQJ99BCACYeBjFXJ3w3AAAYACOG2C0A
Content-Type: application/json

###

GET https://eastus.api.cognitive.microsoft.com/speechtotext/v3.2/transcriptions/5a2b4c39-0a38-49f9-8ecc-17a7983cf573/files/70eba13c-3184-4795-9333-b952576624fc
Ocp-Apim-Subscription-Key: 7cguxqsRWHtwh1P0IAsSlYzTK5dSdhSNsePTqxblqOQUsOtL50YbJQQJ99BCACYeBjFXJ3w3AAAYACOG2C0A
Content-Type: application/json
