# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - speachdemorbb001

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # updated to point to the src directory
  AZURE_FUNCTIONAPP_NAME: 'funcspeechdemorb091' # updated to point to the function name you deployed previously 
  PYTHON_VERSION: '3.12' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build-deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r src/requirements.txt  # Updated path to requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: |
          cd src
          zip -r ../release.zip ./*  # Create zip from src directory content only

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_65E41E684CC54DB696385CCF2F12EC0F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F2562991E53414F884D39612E98C783 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2E9E25C5423F4CBEA5847155A567B9FE }}
          
      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location ${{ secrets.AZURE_LOCATION }}
          
      - name: Deploy Azure Infrastructure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --template-file ./infra/azureFunction.bicep \
              --parameters functionAppName=${{ env.AZURE_FUNCTIONAPP_NAME }} \
              --parameters speechSubscriptionKey=${{ secrets.SPEECH_SUBSCRIPTION_KEY }} \
              --parameters speechRegion=${{ secrets.SPEECH_REGION }} \
              --parameters openaiCompletionsEndpoint=${{ secrets.OPENAI_COMPLETIONS_ENDPOINT }} \
              --parameters openaiCompletionsModel=${{ secrets.OPENAI_COMPLETIONS_MODEL }} \
              --parameters openaiCompletionsKey=${{ secrets.OPENAI_COMPLETIONS_KEY }} \
              --parameters existingCognitiveServicesMSIId=${{ secrets.EXISTING_COGNITIVE_SERVICES_MSI_ID }} \
              --parameters languageSubscriptionKey=${{ secrets.LANGUAGE_SUBSCRIPTION_KEY }} \
              --parameters languageEndpoint=${{ secrets.LANGUAGE_ENDPOINT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-deploy-infra
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_65E41E684CC54DB696385CCF2F12EC0F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F2562991E53414F884D39612E98C783 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2E9E25C5423F4CBEA5847155A567B9FE }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: '${{ env.AZURE_FUNCTIONAPP_NAME }}'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
